In [1]:
import numpy as np
import pandas as pd

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

import warnings
warnings.filterwarnings('ignore')

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [ ]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [ ]:
scaler=MinMaxScaler()
cols=['soil_moisture', 'temperature_c', 'sunlight_hours']
X_scaled=X.copy()
X_scaled[cols]= scaler.fit_transform(X_scaled[cols])
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42,)

In [ ]:
model = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8,activation= 'relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [ ]:
model.compile(optimizer='sgd',loss = 'binary_crossentropy',metrics= ['accuracy'])

In [ ]:
history=model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,
    batch_size=4,
    verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 105ms/step - accuracy: 0.5000 - loss: 0.6888 - val_accuracy: 0.0000e+00 - val_loss: 0.7331
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6857 - val_accuracy: 0.0000e+00 - val_loss: 0.7340
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6834 - val_accuracy: 0.0000e+00 - val_loss: 0.7349
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6811 - val_accuracy: 0.0000e+00 - val_loss: 0.7357
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6786 - val_accuracy: 0.0000e+00 - val_loss: 0.7366
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6770 - val_accuracy: 0.0000e+00 - val_loss: 0.7374
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6757 - val_accuracy: 0.0000e+00 - val_loss: 0.7382
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6732 - val_accuracy: 0.0000e+00 - val_loss: 0.7390
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6713 - val_accuracy: 0.0000e+00 - val_loss: 0.7398
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.6699 - val_accuracy: 0.0000e+00 - val_loss: 0.7405
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.6689 - val_accuracy: 0.0000e+00 - val_loss: 0.7413
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7500 - loss: 0.6675 - val_accuracy: 0.0000e+00 - val_loss: 0.7420
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7500 - loss: 0.6655 - val_accuracy: 0.0000e+00 - val_loss: 0.7426
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.6643 - val_accuracy: 0.2500 - val_loss: 0.7434
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7500 - loss: 0.6615 - val_accuracy: 0.2500 - val_loss: 0.7440
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.6605 - val_accuracy: 0.2500 - val_loss: 0.7446
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7500 - loss: 0.6593 - val_accuracy: 0.2500 - val_loss: 0.7452
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6571 - val_accuracy: 0.2500 - val_loss: 0.7457
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6667 - loss: 0.6559 - val_accuracy: 0.2500 - val_loss: 0.7461
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6546 - val_accuracy: 0.2500 - val_loss: 0.7466
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6533 - val_accuracy: 0.2500 - val_loss: 0.7470
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6524 - val_accuracy: 0.2500 - val_loss: 0.7474
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6514 - val_accuracy: 0.2500 - val_loss: 0.7480
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6517 - val_accuracy: 0.2500 - val_loss: 0.7486
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6479 - val_accuracy: 0.2500 - val_loss: 0.7491
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5833 - loss: 0.6470 - val_accuracy: 0.2500 - val_loss: 0.7497
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6465 - val_accuracy: 0.2500 - val_loss: 0.7501
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6442 - val_accuracy: 0.2500 - val_loss: 0.7507
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6435 - val_accuracy: 0.2500 - val_loss: 0.7513
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5833 - loss: 0.6416 - val_accuracy: 0.2500 - val_loss: 0.7520
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6407 - val_accuracy: 0.2500 - val_loss: 0.7526
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6397 - val_accuracy: 0.2500 - val_loss: 0.7531
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6379 - val_accuracy: 0.2500 - val_loss: 0.7537
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6367 - val_accuracy: 0.2500 - val_loss: 0.7543
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.6356 - val_accuracy: 0.2500 - val_loss: 0.7548
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6343 - val_accuracy: 0.2500 - val_loss: 0.7553
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6330 - val_accuracy: 0.2500 - val_loss: 0.7557
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.6320 - val_accuracy: 0.2500 - val_loss: 0.7562
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6667 - loss: 0.6307 - val_accuracy: 0.2500 - val_loss: 0.7565
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6304 - val_accuracy: 0.2500 - val_loss: 0.7568
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.6285 - val_accuracy: 0.2500 - val_loss: 0.7572
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.6277 - val_accuracy: 0.2500 - val_loss: 0.7575
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6270 - val_accuracy: 0.2500 - val_loss: 0.7578
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6257 - val_accuracy: 0.2500 - val_loss: 0.7580
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6259 - val_accuracy: 0.2500 - val_loss: 0.7582
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6235 - val_accuracy: 0.2500 - val_loss: 0.7585
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.6226 - val_accuracy: 0.2500 - val_loss: 0.7587
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6229 - val_accuracy: 0.2500 - val_loss: 0.7589
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6229 - val_accuracy: 0.2500 - val_loss: 0.7591
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6212 - val_accuracy: 0.2500 - val_loss: 0.7592
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6199 - val_accuracy: 0.2500 - val_loss: 0.7594
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6183 - val_accuracy: 0.2500 - val_loss: 0.7594
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6667 - loss: 0.6169 - val_accuracy: 0.2500 - val_loss: 0.7596
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6667 - loss: 0.6171 - val_accuracy: 0.2500 - val_loss: 0.7597
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.6667 - loss: 0.6152 - val_accuracy: 0.2500 - val_loss: 0.7598
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6667 - loss: 0.6142 - val_accuracy: 0.2500 - val_loss: 0.7598
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6667 - loss: 0.6136 - val_accuracy: 0.2500 - val_loss: 0.7599
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6667 - loss: 0.6124 - val_accuracy: 0.2500 - val_loss: 0.7599
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6667 - loss: 0.6118 - val_accuracy: 0.2500 - val_loss: 0.7600
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.6121 - val_accuracy: 0.2500 - val_loss: 0.7601
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.6109 - val_accuracy: 0.2500 - val_loss: 0.7602
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6667 - loss: 0.6098 - val_accuracy: 0.2500 - val_loss: 0.7603
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.6667 - loss: 0.6086 - val_accuracy: 0.2500 - val_loss: 0.7605
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.6080 - val_accuracy: 0.2500 - val_loss: 0.7605
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6667 - loss: 0.6082 - val_accuracy: 0.2500 - val_loss: 0.7606
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6066 - val_accuracy: 0.2500 - val_loss: 0.7607
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.6059 - val_accuracy: 0.2500 - val_loss: 0.7607
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6667 - loss: 0.6052 - val_accuracy: 0.2500 - val_loss: 0.7608
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.6058 - val_accuracy: 0.2500 - val_loss: 0.7608
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6051 - val_accuracy: 0.2500 - val_loss: 0.7610
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.6034 - val_accuracy: 0.2500 - val_loss: 0.7610
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6023 - val_accuracy: 0.2500 - val_loss: 0.7610
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.6026 - val_accuracy: 0.2500 - val_loss: 0.7609
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.6008 - val_accuracy: 0.2500 - val_loss: 0.7609
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6667 - loss: 0.6006 - val_accuracy: 0.2500 - val_loss: 0.7608
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6667 - loss: 0.6009 - val_accuracy: 0.2500 - val_loss: 0.7608
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5991 - val_accuracy: 0.2500 - val_loss: 0.7608
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5988 - val_accuracy: 0.2500 - val_loss: 0.7608
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5986 - val_accuracy: 0.2500 - val_loss: 0.7607
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5976 - val_accuracy: 0.2500 - val_loss: 0.7605
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5965 - val_accuracy: 0.2500 - val_loss: 0.7605
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5966 - val_accuracy: 0.2500 - val_loss: 0.7604
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5959 - val_accuracy: 0.2500 - val_loss: 0.7603
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.5942 - val_accuracy: 0.2500 - val_loss: 0.7601
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.5935 - val_accuracy: 0.2500 - val_loss: 0.7600
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.5927 - val_accuracy: 0.2500 - val_loss: 0.7599
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6667 - loss: 0.5921 - val_accuracy: 0.2500 - val_loss: 0.7597
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5928 - val_accuracy: 0.2500 - val_loss: 0.7597
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5913 - val_accuracy: 0.2500 - val_loss: 0.7596
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5911 - val_accuracy: 0.2500 - val_loss: 0.7594
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5903 - val_accuracy: 0.2500 - val_loss: 0.7594
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5891 - val_accuracy: 0.2500 - val_loss: 0.7592
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5897 - val_accuracy: 0.2500 - val_loss: 0.7590
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5872 - val_accuracy: 0.2500 - val_loss: 0.7589
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5866 - val_accuracy: 0.2500 - val_loss: 0.7587
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.5861 - val_accuracy: 0.2500 - val_loss: 0.7585
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5853 - val_accuracy: 0.2500 - val_loss: 0.7583
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.5860 - val_accuracy: 0.2500 - val_loss: 0.7580
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5842 - val_accuracy: 0.2500 - val_loss: 0.7579
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.5836 - val_accuracy: 0.2500 - val_loss: 0.7578