In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import string

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,SimpleRNN

import warnings
warnings.filterwarnings('ignore')

In [10]:
df=pd.read_csv("qoute_dataset.csv")
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [11]:
df.shape

(3038, 2)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3038 entries, 0 to 3037
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   quote   3038 non-null   object
 1   Author  3038 non-null   object
dtypes: object(2)
memory usage: 47.6+ KB

In [13]:
quotes= df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [14]:
quotes= quotes.str.lower()

In [15]:
translator= str.maketrans('','',string.punctuation)
quotes= quotes.apply(lambda x:x.translate(translator))

In [16]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [17]:
vocal_size=8978

tok=Tokenizer(num_words=vocal_size)
tok.fit_on_texts(quotes)

In [18]:
word_index= tok.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [19]:
sequence= tok.texts_to_sequences(quotes)

In [20]:
quotes[0]

'“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”'

In [21]:
sequence[0]

[713,
 62,
 29,
 19,
 16,
 946,
 10,
 7,
 5,
 1156,
 8,
 70,
 293,
 10,
 145,
 12,
 809,
 104,
 752,
 70,
 2461]

In [22]:
X= []
y= []

for seq in sequence:
    for i in range(1,len(seq)):
      input_seq= seq[:i]
      output_seq= seq[i]
      X.append(input_seq)
      y.append(output_seq)

In [23]:
len(X)

85270

In [24]:
len(y)

85270

In [25]:
max_len= max(len(x) for x in X)
max_len

745

In [26]:
X_padded= pad_sequences(X,maxlen=max_len,padding='pre')

In [27]:
y=np.array(y)

In [28]:
X_padded.shape

(85270, 745)

In [29]:
y.shape

(85270,)

In [30]:
y

array([ 62,  29,  19, ...,   3, 169, 101])

In [31]:
y_onehot= to_categorical(y,num_classes=vocal_size)
y_onehot

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [32]:
embedding= 50
rnn_units= 128
rnn_model= Sequential()
rnn_model.add(Embedding(input_dim=vocal_size,output_dim=embedding,input_length=max_len))
rnn_model.add(SimpleRNN(units=rnn_units,return_sequences=True))
rnn_model.add(Dense(units=vocal_size,activation='softmax'))

In [33]:
rnn_model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [34]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
lstm_model= Sequential()
lstm_model.add(Embedding(input_dim=vocal_size,output_dim=embedding,input_length=max_len))

lstm_model.add(LSTM(units=rnn_units,return_sequences=True))
lstm_model.add(Dense(units=vocal_size,activation='softmax'))

In [36]:
lstm_model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [37]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [38]:
embedding= 50
rnn_units= 128
rnn_model= Sequential()
rnn_model.add(Embedding(input_dim=vocal_size,output_dim=embedding,input_length=max_len))
rnn_model.add(SimpleRNN(units=rnn_units,return_sequences=False)) # FIX: Changed to False
rnn_model.add(Dense(units=vocal_size,activation='softmax'))

rnn_model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

epochs=10
batch_size= 128
history_rnn=rnn_model.fit(X_padded,y_onehot,epochs=epochs,batch_size=batch_size,validation_split=0.1)

Epoch 1/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 47s 70ms/step - accuracy: 0.0453 - loss: 6.6973 - val_accuracy: 0.0559 - val_loss: 6.5465
Epoch 2/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 76s 65ms/step - accuracy: 0.0618 - loss: 6.5835 - val_accuracy: 0.0670 - val_loss: 6.6234
Epoch 3/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.0680 - loss: 6.4712 - val_accuracy: 0.0732 - val_loss: 6.5557
Epoch 4/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.0828 - loss: 6.0366 - val_accuracy: 0.0805 - val_loss: 6.5190
Epoch 5/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.0922 - loss: 5.8822 - val_accuracy: 0.0876 - val_loss: 6.4981
Epoch 6/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 64ms/step - accuracy: 0.0979 - loss: 5.7417 - val_accuracy: 0.0914 - val_loss: 6.4972
Epoch 7/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 64ms/step - accuracy: 0.1034 - loss: 5.6675 - val_accuracy: 0.0929 - val_loss: 6.5019
Epoch 8/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.1090 - loss: 5.5186 - val_accuracy: 0.0955 - val_loss: 6.5029
Epoch 9/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 64ms/step - accuracy: 0.1148 - loss: 5.3974 - val_accuracy: 0.0984 - val_loss: 6.5125
Epoch 10/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 64ms/step - accuracy: 0.1161 - loss: 5.4308 - val_accuracy: 0.0956 - val_loss: 6.5602

In [39]:
# Redefine the LSTM model with return_sequences=False
lstm_model= Sequential()
lstm_model.add(Embedding(input_dim=vocal_size,output_dim=embedding,input_length=max_len))
lstm_model.add(LSTM(units=rnn_units,return_sequences=False)) # FIX: Changed to False
lstm_model.add(Dense(units=vocal_size,activation='softmax'))

# Recompile the model
lstm_model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

epochs=100
batch_size= 128
history_lstm=lstm_model.fit(X_padded,y_onehot,epochs=epochs,batch_size=batch_size,validation_split=0.1)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 57ms/step - accuracy: 0.0388 - loss: 6.7445 - val_accuracy: 0.0425 - val_loss: 6.6826
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 36s 55ms/step - accuracy: 0.0624 - loss: 6.2942 - val_accuracy: 0.0731 - val_loss: 6.5009
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.0845 - loss: 6.0255 - val_accuracy: 0.0884 - val_loss: 6.4506
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.0987 - loss: 5.8187 - val_accuracy: 0.0969 - val_loss: 6.4184
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1098 - loss: 5.6401 - val_accuracy: 0.1010 - val_loss: 6.4077
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.1191 - loss: 5.4683 - val_accuracy: 0.1047 - val_loss: 6.4178
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1283 - loss: 5.3108 - val_accuracy: 0.1071 - val_loss: 6.4243
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1353 - loss: 5.1648 - val_accuracy: 0.1074 - val_loss: 6.4741
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1432 - loss: 5.0253 - val_accuracy: 0.1088 - val_loss: 6.5079
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1498 - loss: 4.8934 - val_accuracy: 0.1109 - val_loss: 6.5665
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1573 - loss: 4.7634 - val_accuracy: 0.1118 - val_loss: 6.6223
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1649 - loss: 4.6385 - val_accuracy: 0.1121 - val_loss: 6.6765
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1738 - loss: 4.5157 - val_accuracy: 0.1119 - val_loss: 6.7453
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1838 - loss: 4.3953 - val_accuracy: 0.1102 - val_loss: 6.8100
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1955 - loss: 4.2778 - val_accuracy: 0.1136 - val_loss: 6.8899
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2084 - loss: 4.1650 - val_accuracy: 0.1086 - val_loss: 6.9559
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2222 - loss: 4.0564 - val_accuracy: 0.1134 - val_loss: 7.0221
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2352 - loss: 3.9510 - val_accuracy: 0.1126 - val_loss: 7.1010
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2499 - loss: 3.8527 - val_accuracy: 0.1122 - val_loss: 7.1744
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.2632 - loss: 3.7601 - val_accuracy: 0.1102 - val_loss: 7.2663
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.2755 - loss: 3.6745 - val_accuracy: 0.1092 - val_loss: 7.3402
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2885 - loss: 3.5913 - val_accuracy: 0.1072 - val_loss: 7.4211
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.2999 - loss: 3.5153 - val_accuracy: 0.1048 - val_loss: 7.5006
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3107 - loss: 3.4430 - val_accuracy: 0.1067 - val_loss: 7.5729
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.3224 - loss: 3.3735 - val_accuracy: 0.1052 - val_loss: 7.6462
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3325 - loss: 3.3086 - val_accuracy: 0.1052 - val_loss: 7.7215
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3422 - loss: 3.2459 - val_accuracy: 0.1037 - val_loss: 7.7871
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3520 - loss: 3.1845 - val_accuracy: 0.1038 - val_loss: 7.8552
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3624 - loss: 3.1259 - val_accuracy: 0.1040 - val_loss: 7.9281
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3721 - loss: 3.0696 - val_accuracy: 0.1040 - val_loss: 8.0002
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3805 - loss: 3.0143 - val_accuracy: 0.1018 - val_loss: 8.0635
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3889 - loss: 2.9622 - val_accuracy: 0.1018 - val_loss: 8.1188
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3993 - loss: 2.9100 - val_accuracy: 0.1026 - val_loss: 8.1887
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4069 - loss: 2.8609 - val_accuracy: 0.1011 - val_loss: 8.2662
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.4158 - loss: 2.8125 - val_accuracy: 0.1024 - val_loss: 8.3253
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4236 - loss: 2.7657 - val_accuracy: 0.1004 - val_loss: 8.3807
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4316 - loss: 2.7204 - val_accuracy: 0.0996 - val_loss: 8.4440
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4401 - loss: 2.6744 - val_accuracy: 0.0979 - val_loss: 8.4968
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4468 - loss: 2.6328 - val_accuracy: 0.0998 - val_loss: 8.5722
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4549 - loss: 2.5902 - val_accuracy: 0.1005 - val_loss: 8.6346
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4622 - loss: 2.5492 - val_accuracy: 0.0992 - val_loss: 8.6823
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.4699 - loss: 2.5102 - val_accuracy: 0.0984 - val_loss: 8.7606
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4749 - loss: 2.4766 - val_accuracy: 0.0980 - val_loss: 8.8111
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.4823 - loss: 2.4335 - val_accuracy: 0.0957 - val_loss: 8.8636
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4887 - loss: 2.3964 - val_accuracy: 0.0968 - val_loss: 8.9204
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4973 - loss: 2.3602 - val_accuracy: 0.0959 - val_loss: 8.9883
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5037 - loss: 2.3267 - val_accuracy: 0.0938 - val_loss: 9.0493
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5098 - loss: 2.2918 - val_accuracy: 0.0939 - val_loss: 9.1001
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5149 - loss: 2.2594 - val_accuracy: 0.0959 - val_loss: 9.1703
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5221 - loss: 2.2269 - val_accuracy: 0.0945 - val_loss: 9.2066
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5275 - loss: 2.1953 - val_accuracy: 0.0948 - val_loss: 9.2721
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5340 - loss: 2.1642 - val_accuracy: 0.0901 - val_loss: 9.3234
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5391 - loss: 2.1342 - val_accuracy: 0.0943 - val_loss: 9.3854
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5459 - loss: 2.1048 - val_accuracy: 0.0908 - val_loss: 9.4387
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5505 - loss: 2.0754 - val_accuracy: 0.0909 - val_loss: 9.4991
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5559 - loss: 2.0486 - val_accuracy: 0.0909 - val_loss: 9.5380
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5621 - loss: 2.0207 - val_accuracy: 0.0884 - val_loss: 9.6094
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5658 - loss: 1.9955 - val_accuracy: 0.0876 - val_loss: 9.6560
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5722 - loss: 1.9675 - val_accuracy: 0.0889 - val_loss: 9.7135
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 56ms/step - accuracy: 0.5783 - loss: 1.9422 - val_accuracy: 0.0891 - val_loss: 9.7636
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5825 - loss: 1.9162 - val_accuracy: 0.0903 - val_loss: 9.8251
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.5876 - loss: 1.8913 - val_accuracy: 0.0860 - val_loss: 9.8641
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.5918 - loss: 1.8679 - val_accuracy: 0.0874 - val_loss: 9.9195
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5970 - loss: 1.8450 - val_accuracy: 0.0871 - val_loss: 9.9801
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6024 - loss: 1.8234 - val_accuracy: 0.0885 - val_loss: 10.0341
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6068 - loss: 1.7984 - val_accuracy: 0.0861 - val_loss: 10.0843
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6102 - loss: 1.7766 - val_accuracy: 0.0849 - val_loss: 10.1253
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6161 - loss: 1.7570 - val_accuracy: 0.0854 - val_loss: 10.1685
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6190 - loss: 1.7353 - val_accuracy: 0.0887 - val_loss: 10.2492
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6235 - loss: 1.7133 - val_accuracy: 0.0834 - val_loss: 10.2730
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6284 - loss: 1.6942 - val_accuracy: 0.0875 - val_loss: 10.3344
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6321 - loss: 1.6743 - val_accuracy: 0.0839 - val_loss: 10.3920
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6359 - loss: 1.6551 - val_accuracy: 0.0836 - val_loss: 10.4272
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6409 - loss: 1.6359 - val_accuracy: 0.0848 - val_loss: 10.4815
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6446 - loss: 1.6168 - val_accuracy: 0.0828 - val_loss: 10.5302
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.6484 - loss: 1.5977 - val_accuracy: 0.0839 - val_loss: 10.5752
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6525 - loss: 1.5789 - val_accuracy: 0.0813 - val_loss: 10.6414
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6546 - loss: 1.5614 - val_accuracy: 0.0822 - val_loss: 10.6925
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6597 - loss: 1.5462 - val_accuracy: 0.0822 - val_loss: 10.7161
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6625 - loss: 1.5273 - val_accuracy: 0.0819 - val_loss: 10.7666
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6655 - loss: 1.5123 - val_accuracy: 0.0837 - val_loss: 10.8298
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6695 - loss: 1.4951 - val_accuracy: 0.0824 - val_loss: 10.8767
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.6734 - loss: 1.4787 - val_accuracy: 0.0817 - val_loss: 10.9251
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6760 - loss: 1.4687 - val_accuracy: 0.0827 - val_loss: 10.9562
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6795 - loss: 1.4515 - val_accuracy: 0.0819 - val_loss: 11.0117
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6836 - loss: 1.4332 - val_accuracy: 0.0801 - val_loss: 11.0514
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6872 - loss: 1.4170 - val_accuracy: 0.0794 - val_loss: 11.0820
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6893 - loss: 1.4089 - val_accuracy: 0.0820 - val_loss: 11.1541
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6932 - loss: 1.3868 - val_accuracy: 0.0835 - val_loss: 11.2124
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6961 - loss: 1.3728 - val_accuracy: 0.0810 - val_loss: 11.2296
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.6992 - loss: 1.3587 - val_accuracy: 0.0802 - val_loss: 11.2901
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7023 - loss: 1.3470 - val_accuracy: 0.0807 - val_loss: 11.3126
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7050 - loss: 1.3325 - val_accuracy: 0.0800 - val_loss: 11.3700
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7096 - loss: 1.3187 - val_accuracy: 0.0794 - val_loss: 11.4309
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.7099 - loss: 1.3063 - val_accuracy: 0.0785 - val_loss: 11.4640
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.7131 - loss: 1.2937 - val_accuracy: 0.0802 - val_loss: 11.5053
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7172 - loss: 1.2800 - val_accuracy: 0.0807 - val_loss: 11.5586
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.7197 - loss: 1.2677 - val_accuracy: 0.0790 - val_loss: 11.6015
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7217 - loss: 1.2556 - val_accuracy: 0.0800 - val_loss: 11.6521
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7247 - loss: 1.2441 - val_accuracy: 0.0813 - val_loss: 11.6777

In [40]:
lstm_model.save('lstm_model.h5')
rnn_model.save('rnn_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.
WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [41]:
index_to_word= {}
for word,index in word_index.items():
  index_to_word[index]= word

In [42]:
def perdictor(model,tok,text,max_len):
  text= text.lower()
  seq= tok.texts_to_sequences([text])[0]
  seq= pad_sequences([seq],maxlen=max_len,padding='pre')

  pred= model.predict(seq,verbose=0)
  pred_index= np.argmax(pred)
  return index_to_word[pred_index]

In [43]:
seed_text="what is"
next_word= perdictor(lstm_model,tok,seed_text,max_len)
print(next_word)

an

In [47]:
def generate_text(model,tok,seed_text,n_words,max_len):
  for _ in range(n_words):
    next_word= perdictor(model,tok,seed_text,max_len)
    if next_word is "":
      break
    seed_text += " "+ next_word
  return seed_text

In [45]:
seed= "the meaning of life"
generate_text= generate_text(lstm_model,tok,seed,10,max_len)
print(generate_text)

the meaning of life is to be broken but if your dream has to

In [48]:
import pickle

with open ("tokenizer.pkl","wb") as f:
  pickle.dump(tok,f)

In [49]:
with open ("max_len.pkl","wb") as f:
  pickle.dump(max_len,f)